baseURL = "https://yourusername.github.io/"
languageCode = "en-us"
title = "My Portfolio"
theme = "simple-theme"
paginate = 10

[params]
  author = "Your Name"
  description = "A short description about my creative portfolio and blog."

[outputs]
  home = ["HTML", "RSS", "JSON"]
